# Generated by Django 5.0.3 on 2024-03-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('main', models.CharField(help_text='Group of weather parameters (Rain, Snow etc.)', max_length=50, verbose_name='Weather parameters')),
                ('description', models.TextField(help_text='Weather condition within the group', verbose_name='Description')),
                ('temp', models.DecimalField(decimal_places=2, help_text='Temperature. Units – default: kelvin, metric: Celsius, imperial: Fahrenheit', max_digits=10, verbose_name='Temperature')),
                ('feels_like', models.DecimalField(decimal_places=2, help_text='Temperature. This accounts for the human perception of weather. Units – default: kelvin, metric: Celsius, imperial: Fahrenheit', max_digits=10, verbose_name='Human perception of weather')),
                ('visibility', models.PositiveIntegerField(help_text='Average visibility, metres. The maximum value of the visibility is 10 km', verbose_name='Visibility')),
                ('speed', models.DecimalField(decimal_places=2, help_text='Wind speed. Units – default: metre/sec, metric: metre/sec, imperial: miles/hour', max_digits=10, max_length=50, verbose_name='Wind speed')),
                ('datetime', models.DateTimeField(help_text='Time of the forecasted data, Unix, UTC', verbose_name='DateTime')),
                ('sunrise', models.DateTimeField(help_text='Sunrise time, Unix, UTC. For polar areas in midnight sun and polar night periods this parameter is not returned in the response', verbose_name='Sunrise time')),
                ('sunset', models.DateTimeField(help_text='Sunset time, Unix, UTC. For polar areas in midnight sun and polar night periods this parameter is not returned in the response', verbose_name='Sunset time')),
                ('timezone', models.IntegerField(default=0, help_text='Shift in seconds from UTC', verbose_name='Timezone')),
                ('name', models.CharField(help_text='City name. Please note that built-in geocoder functionality has been deprecated.', max_length=50, verbose_name='City name')),
            ],
            options={
                'verbose_name': 'Weather',
                'verbose_name_plural': 'Weather',
                'ordering': ('datetime', 'name'),
            },
        ),
    ]
